# Generated by Django 6.0.4 on 2026-05-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_age_customuser_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(default='general', max_length=255),
        ),
    ]
